export default function Districts(props) {
  let map = {};
  map["Andaman And Nicobar Islands"] = [
    "Nicobar",
    "North And Middle Andaman",
    "South Andaman",
  ];
  map["Andhra Pradesh"] = [
    "Anantapur",
    "Chittoor",
    "East Godavari",
    "West Godavari",
    "Guntur",
    "Kadapa",
    "Krishna",
    "Kurnool",
    "Nellore",
    "Prakasam",
    "Srikakulam",
    "Visakhapatnam",
    "Vizianagaram",
  ];
  map["Arunachal Pradesh"] = [
    "Changlang",
    "Dibang Valley",
    "East Kameng",
    "East Siang",
    "Lohit",
    "Lower Subansiri",
    "Papum Pare",
    "Tawang",
    "Tirap",
    "Upper Siang",
    "Upper Subansiri",
    "West Kameng",
    "West Siang",
  ];
  map["Chandigarh"] = ["Chandigarh"];
  map["Dadra And Nagar Haveli"] = ["Dadra And Nagar Haveli"];
  map["Daman And Diu"] = ["Daman", "Diu"];
  map["Goa"] = ["North Goa", "South Goa"];
  map["Haryana"] = [
    "Ambala",
    "Bhiwani",
    "Faridabad",
    "Fatehabad",
    "Gurgaon",
    "Hisar",
    "Jhajjar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Mahendragarh",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Yamunanagar",
  ];
  map["Himachal Pradesh"] = [
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kinnaur",
    "Kullu",
    "Lahaul And Spiti",
    "Mandi",
    "Shimla",
    "Sirmaur",
    "Solan",
    "Una",
  ];
  map["Jammu And Kashmir"] = ["Kargil", "Leh"];
  map["Madhya Pradesh"] = [
    "Balaghat",
    "Barwani",
    "Betul",
    "Bhind",
    "Bhopal",
    "Chhatarpur",
    "Chhindwara",
    "Damoh",
    "Datia",
    "Dewas",
    "Dhar",
    "Dindori",
    "Guna",
    "Gwalior",
    "Harda",
    "Hoshangabad",
    "Indore",
    "Jabalpur",
    "Jhabua",
    "Katni",
    "Khandwa",
    "Khargone",
    "Mandla",
    "Mandsaur",
    "Morena",
    "Narsinghpur",
    "Neemuch",
    "Panna",
    "Raisen",
    "Rajgarh",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Seoni",
    "Shahdol",
    "Shajapur",
    "Sheopur",
    "Shivpuri",
    "Sidhi",
    "Tikamgarh",
    "Ujjain",
    "Umaria",
    "Vidisha",
  ];
  map["Manipur"] = [
    "Bishnupur",
    "Chandel",
    "Churachandpur",
    "Imphal East",
    "Imphal West",
    "Senapati",
    "Tamenglong",
    "Thoubal",
    "Ukhrul",
  ];
  map["Meghalaya"] = [
    "East Garo Hills",
    "East Jaintia Hills",
    "East Khasi Hills",
    "Ri Bhoi",
    "South Garo Hills",
    "West Garo Hills",
    "West Khasi Hills",
  ];
  map["Mizoram"] = [
    "Aizawl",
    "Champhai",
    "Kolasib",
    "Lawngtlai",
    "Lunglei",
    "Mamit",
    "Saiha",
    "Serchhip",
  ];
  map["Nagaland"] = [
    "Dimapur",
    "Kiphire",
    "Kohima",
    "Longleng",
    "Mokokchung",
    "Mon",
    "Peren",
    "Phek",
    "Tuensang",
    "Wokha",
    "Zunheboto",
  ];
  map["Puducherry"] = ["Karaikal", "Mahe", "Puducherry", "Yanam"];
  map["Uttar Pradesh"] = [
    "Agra",
    "Aligarh",
    "Allahabad",
    "Ambedkarnagar",
    "Amethi",
    "Amroha",
    "Auraiyya",
    "Azamgarh",
    "Badaun",
    "Bagpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bijnor",
    "Bulandshahr",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Faizabad",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddh Nagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur Rural",
    "Kanpur Urban",
    "Kasganj",
    "Kaushambi",
    "Kheri",
    "Kushinagar",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Pilibhit",
    "Pratapgarh",
    "Rae Bareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Shahjahanpur",
    "Shamli",
    "Shravasti",
    "Siddharthnagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi",
  ];
  map["Uttarakhand"] = [
    "Almora",
    "Bageshwar",
    "Chamoli",
    "Champawat",
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Pauri Garhwal",
    "Pithoragarh",
    "Rudraprayag",
    "Tehri Garhwal",
    "Udham Singh Nagar",
    "Uttarkashi",
  ];

  // for First time page load (without selection from DropDown)
  map["None"] = ["None"];

  //   const keys = Object.keys(map);
  //   keys.map((x) => console.log(x));
  //   console.log("keys: " + Object.keys(map));
  //   console.log(map[props]);
  //   console.log(districtObjects);
  return map[props];
}
